export class NavigationConstants {
  static splash = 'splash';
  static home = 'home';
  static payment = 'payment';
  static qrPay = 'QrPay';
  static nfcPay = 'NfcPay';
  static paymentResult = 'PaymentResult';
  static balance = 'balance';
  static balanceDetail = 'balanceDetail';
  static login = 'loginView';
  static announcements = 'announcements';
  static announcementsDetail = 'announcementsDetail';
  static map = 'map';
  static search = 'bus';
}